package it.polimi.ingsw.model.entities.tile;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import it.polimi.ingsw.model.action.Action;
import it.polimi.ingsw.model.entities.card.effects.instant.CardEffectInstant;
import it.polimi.ingsw.model.entities.card.effects.interactive.CardEffectInteractive;
import it.polimi.ingsw.model.player.Player;
import it.polimi.ingsw.network.dto.TileDTO;
import it.polimi.ingsw.visitors.DrawCountVisitor;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a single tile on the game board or in the queue.
 *
 * <p>A tile may be occupied by at most one {@link Player} at a time. It carries
 * two lists of effects: instant effects applied as soon as a player lands on it,
 * and interactive effects that generate pending {@link Action} instances to be
 * resolved by the player. The occupying player is stored both as an object
 * reference (transient, excluded from JSON) and as a nickname string (persisted
 * in JSON) so that the reference can be re-established after deserialization.</p>
 */
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY,
        getterVisibility   = JsonAutoDetect.Visibility.NONE,
        isGetterVisibility = JsonAutoDetect.Visibility.NONE)
public class Tile {

    /** Whether a player is currently occupying this tile. */
    private boolean occupied;

    /** Unique identifier of this tile. */
    private final int id;

    /** Minimum number of players required for this tile to be included in the game. */
    private final int minPlayers;

    /**
     * The player currently occupying this tile.
     * Excluded from JSON serialization; restored via {@link #playerNickname}
     * after deserialization.
     */
    @JsonIgnore
    private Player player;

    /** Instant effects applied to the occupying player when they land on this tile. */
    private final List<CardEffectInstant> instantEffects;

    /** Interactive effects that generate draw actions for the occupying player. */
    private final List<CardEffectInteractive> interactiveEffects;

    /**
     * Nickname of the occupying player, persisted in JSON so that the
     * {@link #player} reference can be re-established after deserialization.
     * Empty string if the tile is unoccupied.
     */
    private String playerNickname;

    /**
     * Constructs a {@code Tile} from its serialized JSON properties.
     *
     * @param id                 unique tile identifier
     * @param minPlayers         minimum number of players for this tile to be active
     * @param instantEffects     instant effects on this tile; {@code null} is
     *                           treated as an empty list
     * @param interactiveEffects interactive effects on this tile; {@code null}
     *                           is treated as an empty list
     * @param occupied           whether the tile is currently occupied
     * @param playerNickname     nickname of the occupying player, or {@code null}
     *                           if unoccupied
     */
    @JsonCreator
    public Tile(@JsonProperty("id") int id,
                @JsonProperty("minPlayers") int minPlayers,
                @JsonProperty("instantEffects") List<CardEffectInstant> instantEffects,
                @JsonProperty("interactiveEffects") List<CardEffectInteractive> interactiveEffects,
                @JsonProperty("occupied") boolean occupied,
                @JsonProperty("playerNickname") String playerNickname) {
        this.id = id;
        this.minPlayers = minPlayers;
        this.instantEffects = instantEffects != null ? instantEffects : new ArrayList<>();
        this.interactiveEffects = interactiveEffects != null ? interactiveEffects : new ArrayList<>();
        this.occupied = occupied;
        this.playerNickname = playerNickname != null ? playerNickname : "";
    }

    /**
     * Applies all instant effects of this tile to the occupying player.
     */
    public void execInstantEffect() {
        for (CardEffectInstant instant : instantEffects) {
            instant.apply(player);
        }
    }

    /**
     * Applies all interactive effects of this tile to the occupying player,
     * collecting the resulting pending actions.
     *
     * @return list of {@link Action} instances generated by the interactive
     *         effects; never {@code null}, may be empty
     */
    public List<Action> execInteractiveEffect() {
        List<Action> actions = new ArrayList<>();
        for (CardEffectInteractive e : interactiveEffects) {
            Action a = e.apply(getPlayer());
            actions.add(a);
        }
        return actions;
    }

    /**
     * Returns the player currently occupying this tile.
     *
     * @return the occupying player, or {@code null} if the tile is unoccupied
     */
    @JsonIgnore
    public Player getPlayer() {
        return player;
    }

    /**
     * Returns whether a player is currently occupying this tile.
     *
     * @return {@code true} if the tile is occupied
     */
    public boolean isOccupied() {
        return occupied;
    }

    /**
     * Places the given player on this tile, updating the occupation state and
     * the persisted nickname. Passing {@code null} is equivalent to calling
     * {@link #removePlayer()}.
     *
     * @param p the player to place, or {@code null} to vacate the tile
     */
    public void setPlayer(Player p) {
        this.player = p;
        this.playerNickname = (p != null) ? p.getNickname() : "";
        occupied = (p != null);
    }

    /**
     * Returns the minimum number of players required for this tile to be
     * included in the game.
     *
     * @return minimum player count
     */
    public int getMinPlayers() {
        return minPlayers;
    }

    /**
     * Returns the unique identifier of this tile.
     *
     * @return tile ID
     */
    public int getId() {
        return id;
    }

    /**
     * Removes the occupying player from this tile, leaving it unoccupied.
     */
    public void removePlayer() {
        this.setPlayer(null);
    }

    /**
     * Applies the queue food bonus to the given player if any of this tile's
     * instant effects provide a food reward.
     *
     * @param p the player to apply the bonus to; must not be {@code null}
     */
    public void applyQueueBonus(Player p) {
        boolean hasFoodEffect = instantEffects.stream().anyMatch(e -> e.getFoodAmount() > 0);
        p.applyQueueFoodBonus(hasFoodEffect);
    }

    /**
     * Converts this tile to a {@link TileDTO} for network transfer, aggregating
     * draw counts and food amounts from its effects.
     *
     * @return a DTO representation of this tile; never {@code null}
     */
    public TileDTO toDTO() {
        DrawCountVisitor visitor = new DrawCountVisitor();
        interactiveEffects.forEach(e -> e.accept(visitor));
        int upDraws = visitor.getUpDraws();
        int downDraws = visitor.getDownDraws();
        int food = instantEffects.stream().mapToInt(CardEffectInstant::getFoodAmount).sum();

        if (isOccupied()) {
            return new TileDTO(occupied, id, minPlayers, player.getNickname(), upDraws, downDraws, food);
        }
        return new TileDTO(occupied, id, minPlayers, "", upDraws, downDraws, food);
    }

    /**
     * Returns the nickname of the player currently occupying this tile, as
     * stored in the persisted field. Returns an empty string if the tile is
     * unoccupied.
     *
     * @return the occupying player's nickname, or an empty string if unoccupied
     */
    public String getPlayerNickname() {
        return playerNickname != null ? playerNickname : "";
    }
}